name: Prueba ejecucion de Script
run-name: Script de JavaScript en ubuntu
on: [push]
jobs:
  execute-script-node:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia actions"
      - run: node --version
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: ls -al
      - run: node app.js
      
  execute-script-deno:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Inicia actions"
      - name: Config deno
        uses: denoland/setup-deno@v2
      - run: deno --version
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: ls -al
      - run: deno app.js