name: Ejecutar al hacer push

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar archivos
        run: ls -la

      - name: Mensaje
        run: echo "¡Se ejecutó el workflow al hacer push!"